[package]
name = "transaction-decoder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.120"
sha2 = "0.10.8"

